REM	Creator:	ANANT PRAKASH SINGH
REM	Year:		2015
REM	Environment:	QBASIC

cls
PLAY"c8 d8 e8 e8 e8 e8 e8 e4 e8 e8 d8 e8 f4"
PLAY"e4 e8 e8 d4 d8 d8<b8>d8 c2"
PLAY"c8 g8 g4 g4 g8 g8 g8 g8 f#4 g8 a8 g4"
PLAY"f4 f8 f8 f4 f8 e8 d8 f8 e2"
PLAY"e4 e8 e8 e8 e4 e8 e8 d8 e8 g8 g8 f8 f4 f4"
PLAY"e4 e8 e8 d4 d8<b8>d8 c2"
PLAY"c8 d8 e8 e8 e4 e8 e8 d8 e8 f2"
PLAY"e8 f8 g8 g8 f4 f8 e8 d8 e2"
PLAY"e4 e4 d8 d8 d8 d8<b8>d8 c2"
PLAY"c8 g8 g8 g8 g8 g8 g8 g8 g8 g4 g8 f8 f8 a8 g4"
PLAY"f4 f8 f8 f4 f8 f8 ed d8 f8 e2"
for i=1 to 5000
next i
PLAY">c8 <b8> c2<"
for i=1 to 10000
next i
PLAY"b8 a8 c2"
for i=1 to 10000
next i
PLAY"c8 c8 d8 d8 e8 e8 d8 e8 f2"


